
# This file is not usable for production. Instead of build, use image: eeacms/zope-2-7-2:latest
web:
  build: .
  environment:
    USERID: 1001
  ports:
  - "80:8080"
  volumes:
  - "/var/tmp/etc-cca:/var/local/website:z"

